2023-04-15 12:03:55.6538|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:04:30.4506|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:05:23.8271|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:07:27.6752|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:22:06.5676|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:22:17.0744|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:e7bf683b-72a5-4a01-9ff4-f4b0435d8a84
Error Number:102,State:1,Class:15
2023-04-15 12:22:20.8092|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:e7bf683b-72a5-4a01-9ff4-f4b0435d8a84
Error Number:102,State:1,Class:15
2023-04-15 12:22:25.1607|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:e7bf683b-72a5-4a01-9ff4-f4b0435d8a84
Error Number:102,State:1,Class:15
2023-04-15 12:22:33.1636|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:e7bf683b-72a5-4a01-9ff4-f4b0435d8a84
Error Number:102,State:1,Class:15
2023-04-15 12:33:02.3950|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:33:03.1160|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:515fe606-4ab5-49dc-a983-3ae81b2c2cfa
Error Number:102,State:1,Class:15
2023-04-15 12:33:10.9198|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:515fe606-4ab5-49dc-a983-3ae81b2c2cfa
Error Number:102,State:1,Class:15
2023-04-15 12:33:18.9369|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:515fe606-4ab5-49dc-a983-3ae81b2c2cfa
Error Number:102,State:1,Class:15
2023-04-15 12:33:26.9451|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:515fe606-4ab5-49dc-a983-3ae81b2c2cfa
Error Number:102,State:1,Class:15
2023-04-15 12:33:34.9534|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:515fe606-4ab5-49dc-a983-3ae81b2c2cfa
Error Number:102,State:1,Class:15
2023-04-15 12:35:53.3375|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:35:59.6521|INFO|ClassHelper.LogHelper|Dapper.CommandDefinition
2023-04-15 12:36:02.4129|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:1b3d00a5-81b8-4790-b819-b051c4554274
Error Number:102,State:1,Class:15
2023-04-15 12:36:04.2275|INFO|ClassHelper.LogHelper|Dapper.CommandDefinition
2023-04-15 12:36:04.7748|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:1b3d00a5-81b8-4790-b819-b051c4554274
Error Number:102,State:1,Class:15
2023-04-15 12:36:13.2409|INFO|ClassHelper.LogHelper|Dapper.CommandDefinition
2023-04-15 12:36:13.3269|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:1b3d00a5-81b8-4790-b819-b051c4554274
Error Number:102,State:1,Class:15
2023-04-15 12:36:21.2450|INFO|ClassHelper.LogHelper|Dapper.CommandDefinition
2023-04-15 12:36:24.0710|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:1b3d00a5-81b8-4790-b819-b051c4554274
Error Number:102,State:1,Class:15
2023-04-15 12:36:53.2813|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:36:53.8983|INFO|ClassHelper.LogHelper|
SELECT d.*
FROM dbo.tblMeasure d
    JOIN
    (
        SELECT r.idDevice,
               date_time = MAX(r.date_time)
        FROM dbo.tblMeasure r
            JOIN
            (
                SELECT idDevice,
                       date_time
                FROM @idDevices, @date_time tmp (idDevice, date_time)
            ) previewTime
                ON previewTime.idDevice = r.idDevice
                   AND previewTime.date_time <= r.date_time
        GROUP BY r.idDevice
    ) s
        ON s.date_time = d.date_time
           AND s.idDevice = d.idDevice;

2023-04-15 12:36:53.8983|INFO|ClassHelper.LogHelper|{ idDevices = System.Collections.Generic.List`1[System.String], date_time = 15/04/2023 12:36:37 }
2023-04-15 12:36:53.9573|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:21f95940-c4d6-4cf3-a983-4e3b0b3eb9ac
Error Number:102,State:1,Class:15
2023-04-15 12:37:01.7045|INFO|ClassHelper.LogHelper|
SELECT d.*
FROM dbo.tblMeasure d
    JOIN
    (
        SELECT r.idDevice,
               date_time = MAX(r.date_time)
        FROM dbo.tblMeasure r
            JOIN
            (
                SELECT idDevice,
                       date_time
                FROM @idDevices, @date_time tmp (idDevice, date_time)
            ) previewTime
                ON previewTime.idDevice = r.idDevice
                   AND previewTime.date_time <= r.date_time
        GROUP BY r.idDevice
    ) s
        ON s.date_time = d.date_time
           AND s.idDevice = d.idDevice;

2023-04-15 12:37:01.7235|INFO|ClassHelper.LogHelper|{ idDevices = System.Collections.Generic.List`1[System.String], date_time = 15/04/2023 12:36:37 }
2023-04-15 12:37:01.8145|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:21f95940-c4d6-4cf3-a983-4e3b0b3eb9ac
Error Number:102,State:1,Class:15
2023-04-15 12:37:09.7355|INFO|ClassHelper.LogHelper|
SELECT d.*
FROM dbo.tblMeasure d
    JOIN
    (
        SELECT r.idDevice,
               date_time = MAX(r.date_time)
        FROM dbo.tblMeasure r
            JOIN
            (
                SELECT idDevice,
                       date_time
                FROM @idDevices, @date_time tmp (idDevice, date_time)
            ) previewTime
                ON previewTime.idDevice = r.idDevice
                   AND previewTime.date_time <= r.date_time
        GROUP BY r.idDevice
    ) s
        ON s.date_time = d.date_time
           AND s.idDevice = d.idDevice;

2023-04-15 12:37:09.7444|INFO|ClassHelper.LogHelper|{ idDevices = System.Collections.Generic.List`1[System.String], date_time = 15/04/2023 12:36:37 }
2023-04-15 12:37:09.8164|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:21f95940-c4d6-4cf3-a983-4e3b0b3eb9ac
Error Number:102,State:1,Class:15
2023-04-15 12:37:17.7438|INFO|ClassHelper.LogHelper|
SELECT d.*
FROM dbo.tblMeasure d
    JOIN
    (
        SELECT r.idDevice,
               date_time = MAX(r.date_time)
        FROM dbo.tblMeasure r
            JOIN
            (
                SELECT idDevice,
                       date_time
                FROM @idDevices, @date_time tmp (idDevice, date_time)
            ) previewTime
                ON previewTime.idDevice = r.idDevice
                   AND previewTime.date_time <= r.date_time
        GROUP BY r.idDevice
    ) s
        ON s.date_time = d.date_time
           AND s.idDevice = d.idDevice;

2023-04-15 12:37:21.9312|INFO|ClassHelper.LogHelper|{ idDevices = System.Collections.Generic.List`1[System.String], date_time = 15/04/2023 12:36:37 }
2023-04-15 12:37:22.0052|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:21f95940-c4d6-4cf3-a983-4e3b0b3eb9ac
Error Number:102,State:1,Class:15
2023-04-15 12:37:25.7601|INFO|ClassHelper.LogHelper|
SELECT d.*
FROM dbo.tblMeasure d
    JOIN
    (
        SELECT r.idDevice,
               date_time = MAX(r.date_time)
        FROM dbo.tblMeasure r
            JOIN
            (
                SELECT idDevice,
                       date_time
                FROM @idDevices, @date_time tmp (idDevice, date_time)
            ) previewTime
                ON previewTime.idDevice = r.idDevice
                   AND previewTime.date_time <= r.date_time
        GROUP BY r.idDevice
    ) s
        ON s.date_time = d.date_time
           AND s.idDevice = d.idDevice;

2023-04-15 12:37:25.7601|INFO|ClassHelper.LogHelper|{ idDevices = System.Collections.Generic.List`1[System.String], date_time = 15/04/2023 12:36:37 }
2023-04-15 12:37:25.8441|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.BaseRepository`1.<QueryListAsync>d__3.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\BaseRepository.Contrib.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:21f95940-c4d6-4cf3-a983-4e3b0b3eb9ac
Error Number:102,State:1,Class:15
2023-04-15 12:42:50.3779|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:42:54.5363|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '@date_time'.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:85a41bf8-3f27-4b1e-b6ef-3b95f273a808
Error Number:102,State:1,Class:15
2023-04-15 12:44:59.8328|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:45:00.4858|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:ddfd7403-28ab-441f-b638-7889ad9e867c
Error Number:102,State:1,Class:15
2023-04-15 12:45:08.3161|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:ddfd7403-28ab-441f-b638-7889ad9e867c
Error Number:102,State:1,Class:15
2023-04-15 12:56:52.3661|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:56:53.1291|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:d009b735-369f-418c-916c-066195154c7b
Error Number:102,State:1,Class:15
2023-04-15 12:57:35.8000|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 12:57:48.7783|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:2ceb5ae0-35a3-4a6a-9d29-4cb24ed2a09e
Error Number:102,State:1,Class:15
2023-04-15 12:57:48.9423|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near ','.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 48
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:2ceb5ae0-35a3-4a6a-9d29-4cb24ed2a09e
Error Number:102,State:1,Class:15
2023-04-15 12:58:50.7800|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:01:19.1298|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:01:19.6050|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:79b40584-6621-4b23-80c3-c81fd331feb9
Error Number:137,State:2,Class:15
2023-04-15 13:01:27.4482|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:79b40584-6621-4b23-80c3-c81fd331feb9
Error Number:137,State:2,Class:15
2023-04-15 13:02:08.9568|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:02:09.2565|ERROR|ClassHelper.LogHelper|System.InvalidOperationException: An enumerable sequence of parameters (arrays, lists, etc) is not allowed in this context
   at Dapper.SqlMapper.GetCacheInfo(Identity identity, Object exampleParameters, Boolean addToCache)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
2023-04-15 13:02:17.0881|ERROR|ClassHelper.LogHelper|System.InvalidOperationException: An enumerable sequence of parameters (arrays, lists, etc) is not allowed in this context
   at Dapper.SqlMapper.GetCacheInfo(Identity identity, Object exampleParameters, Boolean addToCache)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 50
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
2023-04-15 13:09:09.2483|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:09:09.8283|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:579c623e-faf9-48d3-baa4-bfb92e7ec166
Error Number:137,State:2,Class:15
2023-04-15 13:09:17.6566|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:579c623e-faf9-48d3-baa4-bfb92e7ec166
Error Number:137,State:2,Class:15
2023-04-15 13:09:25.6927|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:579c623e-faf9-48d3-baa4-bfb92e7ec166
Error Number:137,State:2,Class:15
2023-04-15 13:09:33.6981|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 54
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:579c623e-faf9-48d3-baa4-bfb92e7ec166
Error Number:137,State:2,Class:15
2023-04-15 13:11:08.3573|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:11:09.0783|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:d372f510-9a03-4b92-813a-9c1b2bed90c4
Error Number:137,State:2,Class:15
2023-04-15 13:11:16.9057|ERROR|ClassHelper.LogHelper|System.Data.SqlClient.SqlException (0x80131904): Must declare the scalar variable "@idDevices0".
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__180_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Dapper.SqlMapper.<QueryAsync>d__33`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at DatabaseAccess.dbBridge.MeasureRepository.<FetchNewData>d__0.MoveNext() in D:\PROJECTS\KSP3\DatabaseAccess\dbBridge\MeasureRepository.cs:line 63
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.Reader.BackgroundWorker.MeasureBackgroundWorker.<RunAsync>d__1.MoveNext() in D:\PROJECTS\KSP3\KSP3.Reader.BackgroudWorker\MeasureBackgroundWorker.cs:line 59
ClientConnectionId:d372f510-9a03-4b92-813a-9c1b2bed90c4
Error Number:137,State:2,Class:15
2023-04-15 13:12:53.6856|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 13:17:11.4586|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:15:51.2705|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:21:56.6827|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:25:27.4028|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:27:53.0654|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:56:54.6844|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:57:42.7328|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 17:59:09.9965|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 18:06:28.2476|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 18:10:19.4812|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 18:20:32.4572|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 18:23:09.8332|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 18:23:46.7193|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:41:53.1553|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:43:11.7856|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:45:21.1324|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:49:04.4448|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:52:22.1545|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:57:02.7083|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:58:04.8465|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
2023-04-15 19:59:51.7607|INFO|ClassHelper.LogHelper|MeasureReaderService RunAsync
