2023-05-29 22:44:17.0441|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:44:50.0602|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:51:36.0873|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:52:18.0360|ERROR|ClassHelper.LogHelper|System.Exception: test
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:53:18.7933|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:53:49.7837|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:55:50.9179|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:56:44.6140|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:57:01.9583|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 22:57:25.6889|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:04:24.4198|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:25:37.0812|ERROR|ClassHelper.LogHelper|System.Exception: An error has occurred.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:25:50.7791|ERROR|ClassHelper.LogHelper|System.Exception: An error has occurred.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:26:42.2329|ERROR|ClassHelper.LogHelper|System.Exception: An error has occurred.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:30:52.9736|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:31:07.5735|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập Tên công thức
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:32:12.9129|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:32:40.9027|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập Tên công thức
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:32:46.7558|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:32:56.4489|ERROR|ClassHelper.LogHelper|System.Exception: Lỗi API: Internal Server Error. http://localhost:8989/SaveDetectorConfig
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:33:22.6074|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:34:24.0733|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập công thức đủ các trường hợp trong khoảng 0-12000.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:37:00.9401|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập Tên công thức
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:37:04.2486|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập công thức đủ các trường hợp trong khoảng 0-12000.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:37:46.8845|ERROR|ClassHelper.LogHelper|System.Exception: Vui lòng nhập công thức đủ các trường hợp trong khoảng 0-12000.
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
2023-05-29 23:39:42.3888|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.ApiClient.<RequestAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\ApiCLient.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.ServiceCaller.BaseCaller.<TryCallServiceAsync>d__0`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\ServiceCaller\BaseCaller.cs:line 17
