2023-05-05 00:06:28.3796|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 00:08:30.2090|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 00:10:22.0259|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 00:56:25.5244|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:03:36.5386|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:07:59.5326|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:09:01.0783|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:14:25.8100|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:15:31.2188|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:16:50.3725|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:18:06.4725|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:19:07.7744|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:19:07.9107|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KSP3.DesktopApp.CustomUI.UserControls.Home.MainScreen.<StartAutoFetch>d__15.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp.CustomUI\UserControls\Home\MainScreen.cs:line 162
2023-05-05 01:22:33.8833|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 01:23:14.0504|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:23:16.3707|ERROR|ClassHelper.LogHelper|System.NullReferenceException: Object reference not set to an instance of an object.
   at KSP3.DesktopApp.Views.frmMain.<<RegisterUI>b__7_3>d.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\Views\frmMain.cs:line 133
2023-05-05 01:23:20.4727|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:23:25.6118|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:23:38.2775|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:23:42.3721|ERROR|ClassHelper.LogHelper|System.NullReferenceException: Object reference not set to an instance of an object.
   at KSP3.DesktopApp.Views.frmMain.<<RegisterUI>b__7_3>d.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\Views\frmMain.cs:line 133
2023-05-05 01:23:46.4965|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:23:51.6008|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:24:06.5938|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:24:08.3226|ERROR|ClassHelper.LogHelper|System.NullReferenceException: Object reference not set to an instance of an object.
   at KSP3.DesktopApp.Views.frmMain.<<RegisterUI>b__7_3>d.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\Views\frmMain.cs:line 133
2023-05-05 01:24:33.7749|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:24:35.2658|ERROR|ClassHelper.LogHelper|System.NullReferenceException: Object reference not set to an instance of an object.
   at KSP3.DesktopApp.Views.frmMain.<<RegisterUI>b__7_3>d.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\Views\frmMain.cs:line 133
2023-05-05 01:24:39.4299|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 01:53:43.6561|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:22:00.8922|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:23:30.4391|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:30:06.3269|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:33:53.5657|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:35:33.5057|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:36:11.7845|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:36:31.2643|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:36:31.3863|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KSP3.DesktopApp.CustomUI.UserControls.Home.MainScreen.<StartAutoFetch>d__15.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp.CustomUI\UserControls\Home\MainScreen.cs:line 162
2023-05-05 02:48:56.8839|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:49:35.8902|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:49:36.0238|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KSP3.DesktopApp.CustomUI.UserControls.Home.MainScreen.<StartAutoFetch>d__15.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp.CustomUI\UserControls\Home\MainScreen.cs:line 162
2023-05-05 02:52:04.4302|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:54:19.3741|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:57:15.1225|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 02:59:43.1090|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 10:30:49.1482|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 10:32:04.9674|ERROR|ClassHelper.LogHelper|System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 127.0.0.1:8989
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at ServiceStack.AsyncServiceClient.<SendWebRequestAsync>d__155`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at KSP3.DesktopApp.UserControls.WCFClient.<TryGetData>d__15`1.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp\UserControls\WCFClient.cs:line 58
2023-05-05 11:22:19.6640|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 11:22:57.4977|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 17:48:00.4538|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 17:49:47.0318|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 17:49:47.1618|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KSP3.DesktopApp.CustomUI.UserControls.Home.MainScreen.<StartAutoFetch>d__15.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp.CustomUI\UserControls\Home\MainScreen.cs:line 162
2023-05-05 17:50:34.6084|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 17:51:37.6159|INFO|ClassHelper.LogHelper|CancelFetchData AutoFetch
2023-05-05 17:51:37.7409|ERROR|ClassHelper.LogHelper|System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at KSP3.DesktopApp.CustomUI.UserControls.Home.MainScreen.<StartAutoFetch>d__15.MoveNext() in D:\PROJECTS\KSP3\KSP3.DesktopApp.CustomUI\UserControls\Home\MainScreen.cs:line 162
